#!/bin/bash

# slim shaaaady

use_dir() {
  local dir="$1"
  if [[ -z "$dir" ]]; then
    dir="$SLIM_TARGET"
  fi
  if [[ -z "$dir" ]]; then
    dir="/hab/pkgs"
  fi
  echo $dir
}

do_generic() {
  for f in $SLIM_ROOT/lib/generic/*; do
    source $f
  done

  # do_strip
  # do_libtool
  # do_static_libs
  do_share_doc
  do_share_locale
  do_include
  # do_broken_links
  do_empty_dirs
}

do_pkgs() {
  for f in $SLIM_ROOT/lib/core/*; do
    source $f
  done
}

do_slim() {
  local dir=$(use_dir $1)
  SLIM_TARGET="$dir"

  do_generic
  do_pkgs
}

if command -v perl >/dev/null; then
  SLIM_ROOT=$(dirname "$(perl -MCwd=realpath -e "print realpath '$0'")")
else
  SLIM_ROOT=$(dirname "$(readlink -f $0)")
fi

do_slim
