#!/bin/bash

do_jdk8() {
  local dir=$(use_dir $1)
  echo "* slim core/jdk8"

  if [[ ! -d $dir/core/jdk8 ]]; then
    return 0
  fi

  rm -rf $dir/core/jdk8/*/*/db # apache derby ???
  rm -rf $dir/core/jdk8/*/*/jre/lib/locale
  rm -rf $dir/core/jdk8/*/*/man
  rm -rf $dir/core/jdk8/*/*/lib/missioncontrol
  rm -rf $dir/core/jdk8/*/*/lib/visualvm
  rm -f $dir/core/jdk8/*/*/javafx-src.zip
  rm -f $dir/core/jdk8/*/*/src.zip
  find $dir/core/jdk8/*/*/ -type f -name '*.bat' -delete

  # if we want to be more agressive, we could also remove javafx when not being
  # used. but it is shipped by default with newer JDK releases.
  # rm -f jre/lib/amd64/libjfxwebkit.so # embedded webkit??
}

do_jdk8
