#!/bin/bash

do_strip() {
  local dir=$(use_dir $1)
  echo "* strip binaries"

  for pkg_dir in $dir/*/*; do
    is_slimmed $pkg_dir && continue

    find $pkg_dir -type f -perm -u+w 2> /dev/null \
      | egrep -v '\.(sh|js|ejs|sqlite|md|markdown|json|yml|xml|svg|png|gif|jpg|css|html|htm|npmignore|keep|txt|h|cc|py|mo)$' \
      | while read -r f; do
        case "$(file -bi "$f")" in
          *application/x-executable*) strip --strip-all "$f";;
          *application/x-sharedlib*) strip --strip-unneeded --strip-debug "$f";;
          *application/x-archive*) strip --strip-debug "$f";;
          *) continue;;
        esac
      done
  done
}
